### ISSUE TITLE
grpc-csharp: version fix

### ISSUE THREAD

**Issue by happyalu** [cobaltspeech/sdk-cubic#59]
`grpc/csharp-cubic/cubic.csproj` maintains a version of the SDK. The README should be updated to change this when we make a new release.

Any other steps that are part of the csharp release of a newer version?

**Comment by jhollowayj** [comment]
As far as I know, we only need to bump the `<Version>1.4.0</Version>` tag in the [cubic.csproj](https://github.com/cobaltspeech/sdk-cubic/blob/master/grpc/csharp-cubic/cubic.csproj#L5) file.
@shahruk10 would be the other person I would double check with.  He's been more involved with C# code over on our Juzu SDK.

**Comment by jhollowayj** [comment]
As a side note We currently push C# packages to the [NuGet Gallery](https://www.nuget.org/packages/Cubic-SDK/).  We could maybe look in to publishing to [GitHub Packages](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-dotnet-cli-for-use-with-github-packages) as well.  NuGet seems to be the standard, so I think we can probably continue to use NuGet instead of using GitHub packages as well.  I imagine it would be a little weird for existing users to transfer/know where to go for updates, etc.

**Comment by shahruk10** [comment]
> 
> 
> As far as I know, we only need to bump the `<Version>1.4.0</Version>` tag in the [cubic.csproj](https://github.com/cobaltspeech/sdk-cubic/blob/master/grpc/csharp-cubic/cubic.csproj#L5) file.
> @shahruk10 would be the other person I would double check with. He's been more involved with C# code over on our Juzu SDK.

Besides the .csproj file, we also need to bump the `VERSION` variable in the [Makefile](https://github.com/cobaltspeech/sdk-cubic/blob/5c18501d1cad3440a408a81c02a764b3a0476808/grpc/Makefile#L29) which builds the package we push / upload to Nuget Gallery
