### ISSUE TITLE
grpc-java: without android?

### ISSUE THREAD

**Issue by happyalu** [cobaltspeech/sdk-cubic#63]
Our docs seem to suggest "Java/Android" in the usage instructions, but I noticed there's no grpc/android or grpc/java directory, but the android code is in examples/android.

Is it worthwhile setting up an SDK that doesn't assume we are building the particular android example app?

**Comment by jhollowayj** [comment]
Great question.  With Android, there are two main ways to bring in dependencies.

1. Download someones source code (sometimes with compiled libraries) and import it manually.
2. Use the Gradle dependencies to automatically download the package as part of your build step.  (Java would use Maven, or maybe Gradle, or _maybe_ Ant)

Currently, our android example uses (1), but that's annoying for end users.  I'd love to migrate to the (2) route, as it should be _much_ easier for other developers to get started _and_ maintain existing applications.

I did see that Github recently add a new Package Manager for npm, docker, maven, nuget (C#), and RubyGems.  I think we should probably take a look into what it would take to publish our packages to their Maven package manager. From what I can tell, we should have free hosting since this is a public repo.  I think [this GitHub Docs webpage](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-gradle-for-use-with-github-packages) should give us a good starting ground for that.  However, I think it might take a day or two to figure out.

Maybe this could be a good task for @iZIVer to take a look at?  
Thoughts?

**Comment by iZIVer** [comment]
Yes, I could do it

**Comment by tumarsal** [comment]
We can install android sdk cross https://jitpack.io/ tool
